require 'rspec'
require 'net/http'
require 'json'
require_relative '../data/static_data'
require_relative '../lib/AuthFunctions'
require_relative '../lib/ProductFunctions'
require_relative '../lib/PlanFunctions'
require_relative '../lib/RunFunctions'
require_relative '../lib/ResultSetFunctions'
require_relative '../lib/ResultFunctions'
require_relative '../lib/StatusFunctions'
require_relative '../lib/AuthFunctions'
require_relative '../../spec/lib/ObjectWrap/http'
class TestManagement
end
