# frozen_string_literal: true

require_relative 'models/AbstractCase'
require_relative 'models/AbstractCasePack'
require_relative 'models/AbstractHistory'
require_relative 'models/AbstractHistoryPack'
require_relative 'models/AbstractPlan'
require_relative 'models/AbstractPlanPack'
require_relative 'models/AbstractProduct'
require_relative 'models/AbstractProductPack'
require_relative 'models/AbstractResult'
require_relative 'models/AbstractResultPack'
require_relative 'models/AbstractResultSet'
require_relative 'models/AbstractResultSetPack'
require_relative 'models/AbstractRun'
require_relative 'models/AbstractRunPack'
require_relative 'models/AbstractStatus'
require_relative 'models/AbstractStatusPack'
require_relative 'models/AbstractSuite'
require_relative 'models/AbstractSuitePack'
require_relative 'models/AbstractToken'
require_relative 'models/AbstractTokenPack'
